# Generated by Django 6.0.3 on 2026-04-06 15:37

import ads.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('width_px', models.PositiveIntegerField()),
                ('height_px', models.PositiveIntegerField()),
                ('ad_type', models.CharField(choices=[('horizontal', 'Yatay Banner'), ('grid_card', 'Grid Kartı')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('grid_interval', models.PositiveIntegerField(default=6, help_text='Her kaç üründen sonra reklam gösterileceği (yalnızca grid_card tipi için)')),
                ('max_ads_in_grid', models.PositiveIntegerField(default=3, help_text='Grid içinde maksimum gösterilecek reklam sayısı (referans)')),
                ('price_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Günlük Fiyat')),
                ('price_weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Haftalık Fiyat')),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Aylık Fiyat')),
                ('price_currency', models.CharField(default='TRY', help_text='Örn: TRY, USD, EUR', max_length=3, verbose_name='Para Birimi')),
            ],
            options={
                'verbose_name': 'Reklam Slotu',
                'verbose_name_plural': 'Reklam Slotları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=200, verbose_name='Reklamveren')),
                ('image', models.ImageField(blank=True, help_text='Boş bırakılırsa CSS placeholder gösterilir', null=True, upload_to=ads.models.ad_image_upload_to, verbose_name='Görsel')),
                ('link_url', models.CharField(default='#', help_text='Reklama tıklandığında yönlendirilecek adres', max_length=500, verbose_name='Hedef URL')),
                ('title', models.CharField(blank=True, help_text='Görselin alt metni ve tooltip olarak kullanılır', max_length=200, verbose_name='Başlık / Alt Metin')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('order', models.PositiveIntegerField(default=0, help_text='Küçük değer önce gösterilir', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adslot', verbose_name='Slot')),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
                'ordering': ['slot', 'order'],
            },
        ),
    ]
