# Generated by Django 6.0.3 on 2026-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='display_duration_seconds',
            field=models.PositiveIntegerField(default=5, help_text='Bu reklamın rotasyonda kaç saniye gösterileceği.', verbose_name='Gösterim Süresi (sn)'),
        ),
    ]
