# Generated by Django 6.0.3 on 2026-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Zamanı')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-posta Gönderildi')),
            ],
            options={
                'verbose_name': 'İletişim Formu Başvurusu',
                'verbose_name_plural': 'İletişim Formu Başvuruları',
                'db_table': 'contact_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterField(
            model_name='consenttext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membershipconsent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profileeditrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signuprequesthistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
