# Generated by Django 6.0.3 on 2026-03-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_buyer_interested_sectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_username',
            field=models.SlugField(blank=True, help_text="URL'de kullanılacak benzersiz firma tanımlayıcısı (örn. izmir-tekstil)", max_length=150, null=True, unique=True, verbose_name='Firma Kullanıcı Adı'),
        ),
    ]
