# Generated by Django 6.0.3 on 2026-03-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_company_username_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileeditrequest',
            name='open_address',
            field=models.TextField(blank=True, null=True, verbose_name='Açık Adres'),
        ),
    ]
