# Generated by Django 6.0.3 on 2026-03-10 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Firma Logosu'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_pending',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos_pending/', verbose_name='Bekleyen Logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_company_profile',
            field=models.BooleanField(default=False, help_text='Aktif edildiğinde firmanın profil sayfası herkese açık olur.', verbose_name='Firma Profilini Göster'),
        ),
        migrations.CreateModel(
            name='TenantLogoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='tenant_logos_requests/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Red Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tenant_logos', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_logo_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_requests', to='accounts.tenant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Logo Talebi',
                'verbose_name_plural': 'Firma Logo Talepleri',
                'db_table': 'accounts_tenantlogorequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tenant_gallery/', verbose_name='Fotoğraf')),
                ('caption_tr', models.CharField(blank=True, max_length=200, verbose_name='Açıklama (TR)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Açıklama (EN)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='accounts.tenant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Galerisi Fotoğrafı',
                'verbose_name_plural': 'Firma Galerisi Fotoğrafları',
                'db_table': 'accounts_tenantphoto',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPhotoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tenant_gallery_requests/', verbose_name='Fotoğraf')),
                ('caption_tr', models.CharField(blank=True, max_length=200, verbose_name='Açıklama (TR)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Açıklama (EN)')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Red Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tenant_photos', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_photo_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_requests', to='accounts.tenant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Fotoğraf Talebi',
                'verbose_name_plural': 'Firma Fotoğraf Talepleri',
                'db_table': 'accounts_tenantphotorequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
