# Generated by Django 6.0.3 on 2026-03-11 19:56

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_company_profile_and_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo_pending',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.tenant_logo_upload_to('logo'), verbose_name='Firma Logosu'),
        ),
        migrations.AlterField(
            model_name='tenantlogorequest',
            name='logo',
            field=models.ImageField(upload_to=accounts.utils.tenant_logo_upload_to('logo'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tenantphoto',
            name='photo',
            field=models.ImageField(upload_to=accounts.utils.tenant_gallery_photo_upload_to('photo'), verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='tenantphotorequest',
            name='photo',
            field=models.ImageField(upload_to=accounts.utils.tenant_gallery_photo_upload_to('photo'), verbose_name='Fotoğraf'),
        ),
    ]
