# Generated by Django 6.0.3 on 2026-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_consolidate_tenant_photo_logo_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Firma E-posta'),
        ),
    ]
