# Generated by Django 6.0.3 on 2026-03-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_company_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='Ürün ID')),
                ('product_title', models.CharField(blank=True, max_length=500, verbose_name='Ürün Başlığı')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Zamanı')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-posta Gönderildi')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='accounts.tenant', verbose_name='Üretici')),
            ],
            options={
                'verbose_name': 'Üretici Sorgu Formu',
                'verbose_name_plural': 'Üretici Sorgu Formları',
                'db_table': 'accounts_producerenquiry',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
