# Generated by Django 6.0.1 on 2026-01-31 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('country', models.CharField(max_length=100, verbose_name='Ülke')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('is_buyer', models.BooleanField(default=False, verbose_name='Alıcı')),
                ('is_producer', models.BooleanField(default=False, verbose_name='Üretici')),
                ('buyer_interested_sectors', models.TextField(blank=True, help_text='Virgülle ayrılmış sektörler', null=True, verbose_name='İlgilenilen Sektörler')),
                ('buyer_quarterly_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Çeyreklik Alım Hacmi (USD)')),
                ('producer_sector', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sektör')),
                ('producer_quarterly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Çeyreklik Satış Hacmi (USD)')),
                ('producer_product_count', models.IntegerField(blank=True, null=True, verbose_name='Yaklaşık Ürün Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
