# Generated by Django 6.0.1 on 2026-01-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=200, verbose_name='Sektör Adı (TR)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Sektör Adı (EN)')),
            ],
            options={
                'verbose_name': 'Sektör',
                'verbose_name_plural': 'Sektörler',
                'ordering': ['name_tr'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='buyer_interested_sectors',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='producer_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='main.sector', verbose_name='Sektör'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buyer_interested_sectors',
            field=models.ManyToManyField(blank=True, related_name='interested_buyers', to='main.sector', verbose_name='İlgilenilen Sektörler'),
        ),
    ]
