# Generated by Django 6.0.1 on 2026-01-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sector_remove_userprofile_buyer_interested_sectors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='producer_sector',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='producer_sectors',
            field=models.ManyToManyField(blank=True, related_name='producers', to='main.sector', verbose_name='Sektörler'),
        ),
    ]
