# Generated by Django 6.0.1 on 2026-01-31 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_producer_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('is_buyer', models.BooleanField(default=False)),
                ('is_producer', models.BooleanField(default=False)),
                ('buyer_interested_sectors_ids', models.TextField(blank=True, null=True)),
                ('buyer_quarterly_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('producer_sectors_ids', models.TextField(blank=True, null=True)),
                ('producer_quarterly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('producer_product_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kayıt Talebi',
                'verbose_name_plural': 'Kayıt Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
