# Generated by Django 6.0.1 on 2026-02-01 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_signuprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=100, verbose_name='Etiket Adı (TR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Etiket Adı (EN)')),
            ],
            options={
                'verbose_name': 'Ürün Etiketi',
                'verbose_name_plural': 'Ürün Etiketleri',
                'ordering': ['name_tr'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(blank=True, max_length=200, verbose_name='Ürün Başlığı (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Ürün Başlığı (EN)')),
                ('description_tr', models.TextField(blank=True, verbose_name='Ürün Açıklaması (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Ürün Açıklaması (EN)')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Fotoğraf 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Fotoğraf 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Fotoğraf 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Üretici')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='main.producttag', verbose_name='Etiketler')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
    ]
