# Generated by Django 6.0.1 on 2026-02-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_producttag_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Onay Durumu'),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Red Nedeni'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_products', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen'),
        ),
    ]
