# Generated by Django 6.0.1 on 2026-02-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_approval_status_product_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(blank=True, max_length=200, verbose_name='Ürün Başlığı (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Ürün Başlığı (EN)')),
                ('description_tr', models.TextField(blank=True, verbose_name='Ürün Açıklaması (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Ürün Açıklaması (EN)')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='product_requests/', verbose_name='Fotoğraf 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='product_requests/', verbose_name='Fotoğraf 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='product_requests/', verbose_name='Fotoğraf 3')),
                ('tags_ids', models.TextField(blank=True, null=True, verbose_name="Etiket ID'leri")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Durum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Red Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL, verbose_name='Üretici')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_products', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
            ],
            options={
                'verbose_name': 'Ürün Talebi',
                'verbose_name_plural': 'Ürün Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
