# Generated by Django 6.0.1 on 2026-02-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.sector', verbose_name='Sektör'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requests', to='main.sector', verbose_name='Sektör'),
        ),
    ]
