# Generated by Django 6.0.1 on 2026-02-05 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_expo_exposignup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Soyad')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Firma Adı')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon Numarası')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Ülke')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('buyer_interested_sectors_ids', models.TextField(blank=True, null=True, verbose_name="İlgilenilen Sektör ID'leri")),
                ('buyer_quarterly_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Çeyreklik Alım Hacmi (USD)')),
                ('producer_sectors_ids', models.TextField(blank=True, null=True, verbose_name="Sektör ID'leri")),
                ('producer_quarterly_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Çeyreklik Satış Hacmi (USD)')),
                ('producer_product_count', models.IntegerField(blank=True, null=True, verbose_name='Yaklaşık Ürün Sayısı')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Durum')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Red Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_edits', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profil Düzenleme Talebi',
                'verbose_name_plural': 'Profil Düzenleme Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
