# Generated by Django 6.0.1 on 2026-02-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profileeditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Üyelik Onayı Verildi'),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Onay IP Adresi'),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi/Saati'),
        ),
        migrations.CreateModel(
            name='MembershipConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Kullanıcı Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('consent_given_at', models.DateTimeField(verbose_name='Onay Tarihi/Saati')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('consent_text_version', models.CharField(default='v1.0', max_length=50, verbose_name='Onay Metni Versiyonu')),
                ('signup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='main.signuprequest', verbose_name='Kayıt Talebi')),
            ],
            options={
                'verbose_name': 'Üyelik Onay Kaydı',
                'verbose_name_plural': 'Üyelik Onay Kayıtları',
                'ordering': ['-consent_given_at'],
            },
        ),
    ]
