# Generated by Django 6.0.1 on 2026-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_add_memberconsent_and_consent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_tr', models.TextField(help_text="Kayıt formunda ve onay popup'ında gösterilecek Türkçe metin.", verbose_name='Onay Metni (Türkçe)')),
                ('text_en', models.TextField(help_text='English text shown in the registration form and confirmation popup.', verbose_name='Consent Text (English)')),
                ('version', models.CharField(default='v1.0', help_text='Değişiklik yapıldığında versiyonu güncelleyin (örn. v1.1). Bu değer onay kayıtlarına işlenir.', max_length=20, verbose_name='Versiyon')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Üyelik Onay Metni',
                'verbose_name_plural': 'Üyelik Onay Metni',
            },
        ),
    ]
