# Generated by Django 6.0.1 on 2026-02-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_consenttext_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='open_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_company',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Hakkında'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='open_address',
            field=models.TextField(blank=True, null=True, verbose_name='Açık Adres'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Web Sitesi'),
        ),
    ]
