# Generated by Django 6.0.1 on 2026-02-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_tenant_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Değiştirilme Tarihi')),
                ('changes', models.JSONField(verbose_name='Değişiklikler')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren')),
                ('signup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.signuprequest', verbose_name='Kayıt Talebi')),
            ],
            options={
                'verbose_name': 'Kayıt Talebi Geçmişi',
                'verbose_name_plural': 'Kayıt Talebi Geçmişi',
                'ordering': ['-changed_at'],
            },
        ),
    ]
