# Generated by Django 6.0.1 on 2026-03-01 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_add_signup_request_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Firma Sahibi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('read_only', 'Read Only')], default='admin', max_length=20, verbose_name='Firma Rolü'),
        ),
    ]
