# Generated by Django 6.0.3 on 2026-03-19 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_producer_enquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=100, verbose_name='Plan Adı (TR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Plan Adı (EN)')),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama (EN)')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Fiyat (TRY)')),
                ('show_company_profile', models.BooleanField(default=False, help_text='Firmanın genel profil sayfasının herkese açık olup olmayacağı.', verbose_name='Firma Profil Sayfası')),
                ('company_username_editable', models.BooleanField(default=False, help_text="Kullanıcının firma URL'sini (company_username) düzenleyip düzenleyemeyeceği.", verbose_name="Firma URL'si Özelleştirme")),
                ('has_business_card', models.BooleanField(default=False, help_text='Firmanın dijital kartvizit sayfasının aktif olup olmadığı.', verbose_name='Dijital Kartvizit')),
                ('display_company_name', models.BooleanField(default=False, help_text='Firma adının alıcı panosundaki ürün kartlarında ve ürün detay sayfasında görüntülenip görüntülenmeyeceği.', verbose_name='Firma Adı Görünürlüğü')),
                ('display_open_address', models.BooleanField(default=False, help_text='Açık adresin ürün detay sayfasında görüntülenip görüntülenmeyeceği.', verbose_name='Açık Adres Görünürlüğü')),
                ('display_city', models.BooleanField(default=False, help_text='Şehrin ürün detay sayfasında görüntülenip görüntülenmeyeceği.', verbose_name='Şehir Görünürlüğü')),
                ('display_phone', models.BooleanField(default=False, help_text='Telefon numarasının ürün detay sayfasındaki iletişim formunda görüntülenip görüntülenmeyeceği.', verbose_name='Telefon Görünürlüğü')),
                ('display_email', models.BooleanField(default=False, help_text='E-posta adresinin ürün detay sayfasındaki iletişim formunda görüntülenip görüntülenmeyeceği.', verbose_name='E-posta Görünürlüğü')),
                ('display_website', models.BooleanField(default=False, help_text='Web sitesinin ürün detay sayfasındaki iletişim formunda görüntülenip görüntülenmeyeceği.', verbose_name='Web Sitesi Görünürlüğü')),
                ('max_active_products', models.PositiveIntegerField(blank=True, help_text='Boş bırakılırsa sınırsız ürün aktif edilebilir.', null=True, verbose_name='Maksimum Aktif Ürün Sayısı')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Plan')),
            ],
            options={
                'verbose_name': 'Abonelik Planı',
                'verbose_name_plural': 'Abonelik Planları',
                'db_table': 'subscriptions_plan',
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('started_at', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('expires_at', models.DateField(blank=True, help_text='Boş bırakılırsa abonelik süresiz olarak devam eder.', null=True, verbose_name='Bitiş Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Atayan Admin')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.tenant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Aboneliği',
                'verbose_name_plural': 'Firma Abonelikleri',
                'db_table': 'subscriptions_tenantsubscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
