# Generated by Django 6.0.3 on 2026-03-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='viewer_sees_all',
            field=models.BooleanField(default=False, help_text='Bu plana sahip kullanıcı, diğer üreticilerin abonelik planından bağımsız olarak tüm firma adı, adres, şehir, telefon, e-posta ve web sitesi bilgilerini görebilir.', verbose_name='Tüm Üretici Bilgilerini Gör'),
        ),
    ]
