# Generated by Django 6.0.3 on 2026-04-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_premium_viewer_sees_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Kampanya Başlığı (TR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Kampanya Başlığı (EN)')),
                ('description_tr', models.TextField(verbose_name='Açıklama (TR)')),
                ('description_en', models.TextField(verbose_name='Açıklama (EN)')),
                ('valid_from', models.DateField(verbose_name='Kampanya Başlangıcı')),
                ('valid_until', models.DateField(verbose_name='Kampanya Bitiş Tarihi')),
                ('trial_months', models.PositiveSmallIntegerField(default=0, help_text='Kampanya kapsamında verilen ücretsiz deneme süresi (ay). 0 ise deneme yok.', verbose_name='Ücretsiz Deneme Süresi (Ay)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='subscriptions.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Kampanyası',
                'verbose_name_plural': 'Plan Kampanyaları',
                'db_table': 'subscriptions_plancampaign',
                'ordering': ['-valid_until'],
            },
        ),
    ]
