# Generated by Django 6.0.3 on 2026-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_id_alter_productrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_showroom',
            field=models.BooleanField(default=False, help_text='İşaretlenirse firma profil sayfasında görüntülenir.', verbose_name='Vitrin Ürünü'),
        ),
    ]
