# Generated by Django 6.0.3 on 2026-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_product_in_showroom_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Fotoğraf 1'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Fotoğraf 2'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Fotoğraf 3'),
        ),
    ]
