# Generated by Django 6.0.3 on 2026-03-11 18:43

import catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_change_product_request_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.product_photo_upload_to('photo1'), verbose_name='Fotoğraf 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.product_photo_upload_to('photo2'), verbose_name='Fotoğraf 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.product_photo_upload_to('photo3'), verbose_name='Fotoğraf 3'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.product_photo_upload_to('photo1'), verbose_name='Fotoğraf 1'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.product_photo_upload_to('photo2'), verbose_name='Fotoğraf 2'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.product_photo_upload_to('photo3'), verbose_name='Fotoğraf 3'),
        ),
    ]
