# Generated by Django 6.0.3 on 2026-04-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_standardize_photo_upload_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_showroom',
        ),
    ]
